variables:
 vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
    - template: /.azure/pipelines/build/build-ci.yml
      parameters:
        Pool: $(vmImageName)
