trigger:
- main

variables:
 vmImageName: 'ubuntu-latest'
 version: '1.0'

name: $(version).$(rev:r)

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
    - template: /.azure/pipelines/build/build-rm.yml
      parameters:
        Pool: $(vmImageName)

- stage: Nuget_Deployment
  displayName: 'Deploy Nuget'
  jobs:
  - template: /.azure/pipelines/deploy/deploy-rm.yml
    parameters:
      Pool: $(vmImageName)
      Environment: NUGET
      NugetFeed: '67c823c6-80bd-4950-9961-401ef86a5019'
