parameters:
- name: 'Pool'
  type: string
  default: 'ubuntu-latest'
- name: 'Environment'
  type: string
- name: 'NugetFeed'
  type: string


jobs:
- deployment: Deployment
  displayName: "Deploy to ${{ parameters.Environment }}"
  environment: ${{ parameters['Environment'] }}
  pool:
    vmImage: ${{ parameters['Pool'] }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DotNetCoreCLI@2
          displayName: 'dotnet push'
          inputs:
            command: push
            packagesToPush: '$(Pipeline.Workspace)/drop/*.nupkg'
            publishVstsFeed: '${{ parameters.NugetFeed }}'
